$background = rgb({{colors.background.default.hex_stripped}})
$foreground = rgb({{colors.on_background.default.hex_stripped}})
$primary = rgb({{colors.primary.default.hex_stripped}})
$onPrimary = rgb({{colors.on_primary.default.hex_stripped}})
$surfaceVariant = rgb({{colors.surface_variant.default.hex_stripped}})
$onSurfaceVariant = rgb({{colors.on_surface_variant.default.hex_stripped}})
$tertiary = rgb({{colors.tertiary.default.hex_stripped}})
$error = rgb({{colors.error.default.hex_stripped}})
