# The basic colors
foreground              #{{colors.on_surface.default.hex_stripped}}
background              #{{colors.background.default.hex_stripped}}
selection_foreground    #{{colors.surface.default.hex_stripped}}
selection_background    #{{colors.primary.default.hex_stripped}}

# Cursor colors
cursor                  #{{colors.primary.default.hex_stripped}}
cursor_text_color       #{{colors.on_primary.default.hex_stripped}}

# URL underline color
url_color               #{{colors.tertiary.default.hex_stripped}}

# Window borders
active_border_color     #{{colors.primary.default.hex_stripped}}
inactive_border_color   #{{colors.surface_variant.default.hex_stripped}}

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar
active_tab_foreground   #{{colors.surface.default.hex_stripped}}
active_tab_background   #{{colors.primary.default.hex_stripped}}
inactive_tab_foreground #{{colors.on_surface_variant.default.hex_stripped}}
inactive_tab_background #{{colors.surface.default.hex_stripped}}
tab_bar_background      #{{colors.surface.default.hex_stripped}}

# Colors for marks (marked text in the terminal)
mark1_foreground    #{{colors.surface.default.hex_stripped}} 
mark1_background    #{{colors.primary.default.hex_stripped}} 
mark2_foreground    #{{colors.surface.default.hex_stripped}}  
mark2_background    #{{colors.secondary.default.hex_stripped}}  
mark3_foreground    #{{colors.surface.default.hex_stripped}}
mark3_background    #{{colors.tertiary.default.hex_stripped}}   
# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

