$background = rgb(101418)
$foreground = rgb(e1e2e8)
$primary = rgb(9fcafd)
$onPrimary = rgb(003257)
$surfaceVariant = rgb(42474e)
$onSurfaceVariant = rgb(c3c7cf)
$tertiary = rgb(d6bee5)
$error = rgb(ffb4ab)
