# The basic colors
foreground              #e1e2e8
background              #101418
selection_foreground    #101418
selection_background    #9fcafd

# Cursor colors
cursor                  #9fcafd
cursor_text_color       #003257

# URL underline color
url_color               #d6bee5

# Window borders
active_border_color     #9fcafd
inactive_border_color   #42474e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar
active_tab_foreground   #101418
active_tab_background   #9fcafd
inactive_tab_foreground #c3c7cf
inactive_tab_background #101418
tab_bar_background      #101418

# Colors for marks (marked text in the terminal)
mark1_foreground    #101418 
mark1_background    #9fcafd 
mark2_foreground    #101418  
mark2_background    #bac8db  
mark3_foreground    #101418
mark3_background    #d6bee5   
# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

